name: jsbank_remittance
version: 1.0.0+1
publish_to: none
description: App for JSBank Remittance
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  google_fonts: ^2.1.0
  flutter_svg: 0.22.0
  currency_picker: ^2.0.5
  json_api: ^5.0.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

